[project]
name = "market-data-lakehouse-analytics"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.13"

authors = [
  { name = "joaobarreto27", email = "joao.vito1951@gmail.com" }
]
dependencies = [
  "requests>=2.32.5,<3.0.0",
  "pyspark (==3.5.4)",
  "pydantic>=2.12.5,<3.0.0",
  "pandera>=0.28.1,<0.29.0",
  "pandas>=2.3.3,<3.0.0",
  "python-dotenv>=1.2.1,<2.0.0",
  "pyarrow (>=23.0.0,<24.0.0)",
  "setuptools (>=82.0.1,<83.0.0)",
  "streamlit (>=1.55.0,<2.0.0)",
  "boto3 (>=1.42.79,<2.0.0)",
  "botocore[crt] (>=1.42.79,<2.0.0)",
  "watchdog (>=6.0.0,<7.0.0)"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["worker*", "infrastructure*", "dashboard*"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "B", "I", "D"]
ignore = ["D203", "D213"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
files = ["src"]
mypy_path = ["src"]
explicit_package_bases = true
namespace_packages = true
ignore_missing_imports = true

[tool.taskipy.tasks]
format = "ruff format ."
fix = "ruff check . --fix"
commit = "pre-commit run --all-files"
typecheck = "mypy src"
security = "bandit -r src -s B101"
audit = "pip-audit"
ci = """
task format
task fix
task typecheck
task security
task audit
task commit
"""

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
